### ISSUE TITLE
Problem initial start

### ISSUE THREAD

**Issue by frsdxr** [knopkem/dicomweb-proxy#122] opened 2023-05-30 22:37 UTC
hello,
i run new installion error message

root@backup:/opt/dicomweb-proxy-master# npm start

> dicomweb-proxy@1.8.1 start
> ts-node src/app.ts

Error: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /opt/dicomweb-proxy-master/node_modules/dicom-dimse-native/build/Release/dcmtk.node)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1275:18)
    at Module.load (node:internal/modules/cjs/loader:1069:32)
    at Function.Module._load (node:internal/modules/cjs/loader:904:12)
    at Module.require (node:internal/modules/cjs/loader:1093:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at bindings (/opt/dicomweb-proxy-master/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/opt/dicomweb-proxy-master/node_modules/dicom-dimse-native/index.js:4:32)
    at Module._compile (node:internal/modules/cjs/loader:1191:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1245:10)
    at Object.require.extensions.<computed> [as .js] (/opt/dicomweb-proxy-master/node_modules/ts-node/src/index.ts:1608:43) {
  code: 'ERR_DLOPEN_FAILED'
}

my system is ubuntu 16.04

**Comment by knopkem** [comment] 2023-05-31 06:36
Hi,
this is because the latest linux version was build with ubuntu 22.04 LTS and glibc runtime is newer. Will setup an older ubuntu VM and rebuild to make it more backward compatible (again). Will let you know once done. Cheers

**Comment by ruben-cruz** [comment] 2023-07-03 11:33
Hi @knopkem,

I'm getting the same error when doing 'npm start'. Do you know how can I fix this?

> dicomweb-proxy@1.6.4 start
> ts-node src/app.ts

Error: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /opt/dicomweb-proxy/node_modules/dicom-dimse-native/build/Release/dcmtk.node)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1057:18)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at bindings (/opt/dicomweb-proxy/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/opt/dicomweb-proxy/node_modules/dicom-dimse-native/index.js:4:32)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.require.extensions.<computed> [as .js] (/opt/dicomweb-proxy/node_modules/ts-node/src/index.ts:1608:43)

**Comment by knopkem** [comment] 2023-07-04 09:47
@ruben-cruz see my previous answer, it's the same for you (didn't yet have the time to do it, but it's on the agenda)

**Comment by ruben-cruz** [comment] 2023-07-04 10:06
@knopkem do you have any guide or instructions on how to do that? Something that I can read and follow to make it compatible with GLIBC_2.28. And if I succeed I'm glad to publish so others can use.

**Comment by knopkem** [comment] 2023-07-04 22:26
@ruben-cruz thanks for asking to help, but I guess this wouldn't be easy as only I can upload the precompiled binaries to my github repo (and I would not trust any binaries from third party). Anyway, the issue comes from the native bindings to dcmtk, see this project: https://github.com/knopkem/dicom-dimse-native. The issue is that when I published the latest version (as a prebuild) I used a recent (current 22.04 LTS) version of ubuntu, so the c runtime needs to be same or newer. When trying to install dicomweb-proxy or pacs to an older ubuntu (or similar) linux than you will get the error you have.
In principal, one can always compile the dicom-dimse-native on any target system, which should not be too complicated (see readme on that repo) however, this does not include support for unicode characters and jpeg2000. For this you need more dependencies (and this is not documented).
So, I already prepared an old (ubuntu 14) system and setup the build chain. Will publish a new version soon, so than hopefully it should start working for you again.

**Comment by ruben-cruz** [comment] 2023-07-05 08:00
thank you @knopkem. Will you generate a new release v2.4.2 for [dicom-dimse-native](https://github.com/knopkem/dicom-dimse-native)? Sorry to bother you with this, but I'm trying to implement that on a client and I'm stuck on this problem...

**Comment by knopkem** [comment] 2023-07-05 09:35
@ruben-cruz , will publish a new version soon. What OS and version do you intend of installing it to?

**Comment by ruben-cruz** [comment] 2023-07-05 09:47
@knopkem thank you again. The OS is: Red Hat Enterprise Linux release 8.6 (Ootpa).

**Comment by ruben-cruz** [comment] 2023-07-06 14:58
hi @knopkem, sorry to bother you with this, but did you manage to build and publish a new version of dicom-dimse-native? Thanks.

**Comment by knopkem** [comment] 2023-07-06 18:02
Hi @ruben-cruz, it's done. Let me know if it works now. Cheers

**Comment by ruben-cruz** [comment] 2023-07-06 21:40
Hi @knopkem, it worked like a charm. Thank you very much for your time and help! I'm very grateful for your help. Cheers.

**Comment by knopkem** [comment] 2023-07-07 10:15
@frsdxr closing as it should now be fixed with the latest version. Reopen in case of issues.

**Closed by knopkem** 2023-07-07 10:15 UTC
