### ISSUE TITLE
[Override index.umd.js] cannot open image when click any item on the study list

### ISSUE THREAD

**Issue by dinhnam2901** [knopkem/dicomweb-proxy#6] opened 2020-09-01 08:53 UTC
Hi you.
When I build a file of ohif 4.2.3 as ohif/platform/viewer/dist/index.umd.js and then override it into dicomweb-proxy
/public/viewer/index.umd.js.
I run the project, and I see the list of study at home page. But, When I click on any item on study list to open image, so much errors will occur repeated with one type only is: 'Uncaught (in promise) Error: decodeTask: imageFrame.pixelData is undefined after decoding
    at index.umd.js:2'
![error](https://user-images.githubusercontent.com/20145650/91828894-ede33380-ec6a-11ea-9f2b-34e806c275c8.png)

Can you help me to find what the problem in this case ?
Thank you!

**Comment by knopkem** [comment] 2020-09-01 08:59
Hi, this is a bug in the recent versions of OHIF. The problem is that wadouri is not really compliant to dicomweb standard anymore.
I have supplied a patch, but it's not merged: https://github.com/OHIF/Viewers/pull/1785

You can:
* Fork OHIF and apply my patch
* use wadors with dicomweb (experimental for now), checkout the branch: deepMeta and try again, but you might need to use the progressive build (not the umd build). I will try to get a new master out asap that uses wadors by default, so this is 3rd option
* wait for a new version of dicomweb-proxy

**Comment by dinhnam2901** [comment] 2020-09-01 09:51
I apply your patch and it work correctly.
Thank you so much!

**Closed** 2020-09-01 09:52 UTC

**Comment by eanzuresb** [comment] 2021-01-13 20:07
Hi, i have installed the DCM4CHEE pacs in debian 9, and i installed dicomweb-proxy fot can to used the ohif viewer, but when i click to see and atudy the images don`t displays, how can i fix this issue? how can i apply your patch? Help Please!!!!

**Comment by knopkem** [comment] 2021-01-13 21:06
Do you use the build in OHIF viewer or a new build? You don't need to patch
anything for build-in. Can you show what the consol (F12) prints?

**Comment by eanzuresb** [comment] 2021-01-13 21:14
![Captura de Pantalla 2021-01-13 a la(s) 15 08 38](https://user-images.githubusercontent.com/77411745/104510934-8f7f7780-55b1-11eb-9b7a-70fd801b713c.png)

Hi! Thank you for your quick response, this is what the console shows

**Comment by eanzuresb** [comment] 2021-01-13 21:33
I installed by both ways (npm and source) from this: https://github.com/knopkem/dicomweb-prox

And with c-get and c-move and i get the same errors, i have the DCM4CHEE 2.18.3 in debian 9

**Comment by knopkem** [comment] 2021-01-14 09:50
So, first of all you don't need to patch anything when using the build in OHIF viewer (already patched).
The issue is likely a problem between the PACS and the proxy and not between OHIF and the proxy.
Did you register the proxy on DCM4CHEE, this might also be needed for C-GET but definitely is for C-MOVE.
I would recommend to enable verbose logging in the config file and see if there is anything in the log folder that gives a clue.
Also if possible use DCM4CHEE 5 (arc light) which comes with build in DICOMWEB support (hence you don't need this proxy, it will be faster)

**Comment by eanzuresb** [comment] 2021-01-16 18:56
Ok, thank you so much, I'm going to use arc light then
